services:
  - type: web
    name: rowdy-cup-scoreboard-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: cd /opt/render/project/src && node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /_health 